[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ssqlt-prototype"
version = "0.0.0dev0"
dependencies = ["moz_sql_parser"]
requires-python = ">= 3.11"
authors = [
    {"name" = "Aidan Bailey", email = "BLYAID001@myuct.ac.za"}
]
maintainers = [
    {"name" = "Aidan Bailey", email = "BLYAID001@myuct.ac.za"}
]
description = "A prototype for generating Semantic SQL Transducer bindings"
readme = {file = "README.md", content-type = "text/markdown" }
license = {file = "LICENSE"}
keywords = []
classifiers = [
    "License :: OSI Approved :: GNU Lesser General Public License v2 (LGPLv2)",
]

[project.urls]
Repository = "https://github.com/unibz-krdb/ssqlt-prototype"
